pcl_verbosity_level: 'ERROR'                                    # VERBOSE | DEBUG | INFO | WARN | ERROR | ALWAYS || ALWAYS -> no console output
ros_verbosity_level: 'INFO'                                     #           DEBUG | INFO | WARN | ERROR | FATAL

localization_point_type: 'PointXYZRGBNormal'

message_management:
    use_odom_when_transforming_cloud_to_map_frame: false
    invert_cloud_to_map_transform: false
    invert_registration_transformation: true
    invert_initial_poses_from_msgs: true
    initial_pose_msg_needs_to_be_in_map_frame: false
    minimum_number_of_points_in_ambient_pointcloud: 10
    circular_buffer_clear_inserted_points_if_registration_fails: false
#    circular_buffer_require_reception_of_pointcloud_msgs_from_all_topics_before_doing_registration: true
#    minimum_number_points_ambient_pointcloud_circular_buffer: 2500
#    maximum_number_points_ambient_pointcloud_circular_buffer: 2500

reference_pointclouds:
    republish_reference_pointcloud_after_successful_registration: true

publish_topic_names:
    publish_aligned_pointcloud_only_if_there_is_subscribers: false
